[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[build.environment]
  NODE_VERSION = "18"

# Configure secrets scanning to ignore documentation files
[build.processing.secrets]
  enabled = true
  omit_paths = [
    "*.md",
    "docs/*",
    "server/README.md",
    "NETLIFY_DEPLOYMENT.md",
    "dist/*",
    "dist/assets/*"
  ]
